version: "3"

services:
  postgres-sonar:
    image: postgres:11.5
    container_name: postgres-sonar
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./postgresql/postgresql:/var/lib/postgresql
      - ./postgresql/postgresql_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:7.9-community
    container_name: sonarqube
    ports:
      - 9002:9000
    environment:
      - sonar.jdbc.username=sonar
      - jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://postgres-sonar:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    depends_on: 
      - postgres-sonar

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - 8082:8080
      - 50002:50000
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home

  rundeck:
    image: rundeck/rundeck:3.1.3
    container_name: rundeck
    ports:
      - 4442:4440
    volumes:
      - ./rundeck/rundeck_data:/home/rundeck/server/data

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions: